# Generated by Django 4.0.5 on 2022-10-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(max_length=100)),
                ('summary', models.TextField(max_length=100)),
                ('highschool', models.TextField(max_length=100)),
                ('seniorschool', models.TextField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('previous_work', models.TextField(max_length=400)),
                ('skills', models.TextField(max_length=400)),
                ('fathername', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
